/**
 * TemplateConstraints - 模板约束系统
 *
 * 实施尺寸保护、动画保护、样式约束，确保用户调整不会破坏模板专业性
 */

class TemplateConstraints {
  constructor() {
    this.constraints = new Map()
    this.validators = new Map()
    this.initialized = false
  }

  /**
   * 初始化约束系统
   */
  async initialize() {
    if (this.initialized) return

    this.setupGlobalConstraints()
    this.setupLayerConstraints()
    this.setupValidationRules()
    this.setupRecoveryMechanisms()

    this.initialized = true
    console.log('模板约束系统已初始化')
  }

  /**
   * 设置全局约束
   */
  setupGlobalConstraints() {
    this.constraints.set('global', {
      // 尺寸限制
      size: {
        minWidth: 320,
        minHeight: 240,
        maxWidth: 3840,
        maxHeight: 2160,
        aspectRatios: ['16:9', '4:3', '1:1', '21:9']
      },

      // 颜色限制
      colors: {
        allowedPalettes: ['professional', 'vibrant', 'minimal', 'warm'],
        contrastRatio: { min: 4.5, preferred: 7.0 },
        brandColors: ['#007AFF', '#FFD700', '#FF6B6B', '#4ECDC4', '#9B59B6']
      },

      // 字体限制
      typography: {
        allowedFonts: [
          'PingFang SC',
          'Helvetica Neue',
          'Microsoft YaHei',
          'Noto Sans CJK',
          'system-ui'
        ],
        fontSizeRange: { min: 12, max: 72 },
        lineHeightRange: { min: 1.2, max: 2.0 }
      },

      // 动画限制
      animation: {
        allowedTypes: ['fade', 'slide', 'scale', 'rotate', 'bounce'],
        durationRange: { min: 0.1, max: 2.0 },
        easingFunctions: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out'],
        maxConcurrentAnimations: 3
      },

      // 元素限制
      elements: {
        maxElementsPerSlide: 10,
        maxTextLength: 200,
        maxImageSize: 5 * 1024 * 1024, // 5MB
        allowedImageFormats: ['jpg', 'png', 'webp', 'svg']
      }
    })
  }

  /**
   * 设置层级特定约束
   */
  setupLayerConstraints() {
    // 固定层约束
    this.constraints.set('fixed', {
      modifiable: false,
      removable: false,
      properties: {
        position: {
          allowed: ['top-left', 'top-right', 'bottom-left', 'bottom-right', 'center', 'fullscreen'],
          margins: { min: 20, max: 100 }
        },
        size: {
          pip: { min: 160, max: 400 },
          card: { min: 300, max: 800 },
          overlay: { exact: 'fullscreen' }
        },
        style: {
          borderRadius: { min: 0, max: 50 },
          borderWidth: { min: 0, max: 5 },
          opacity: { min: 0.1, max: 1.0 }
        },
        animation: {
          duration: { min: 0.1, max: 0.5 },
          delay: { min: 0, max: 0.2 }
        }
      }
    })

    // 动态层约束
    this.constraints.set('dynamic', {
      modifiable: false,
      removable: false,
      properties: {
        content: {
          autoGenerated: true,
          editable: false
        },
        layout: {
          autoPosition: true,
          collisionDetection: true
        },
        animation: {
          type: 'inherit', // 继承固定层动画
          syncWithContainer: true
        }
      }
    })

    // 可调整层约束
    this.constraints.set('adjustable', {
      modifiable: true,
      removable: true,
      properties: {
        content: {
          maxLength: { title: 20, description: 100, caption: 50 },
          allowedTypes: ['text', 'image', 'icon', 'shape'],
          validation: {
            text: 'no-empty',
            image: 'valid-format',
            url: 'valid-url'
          }
        },
        position: {
          allowed: ['relative', 'absolute'],
          snapTo: ['grid', 'center', 'edges'],
          collisionAvoidance: true
        },
        style: {
          colors: 'from-palette',
          fonts: 'from-allowed',
          spacing: { min: 4, max: 32 }
        },
        animation: {
          optional: true,
          duration: { min: 0.2, max: 1.0 },
          triggers: ['hover', 'click', 'auto']
        }
      }
    })
  }

  /**
   * 设置验证规则
   */
  setupValidationRules() {
    // 尺寸验证器
    this.validators.set('size', (value, constraints) => {
      if (!constraints) return { valid: true }

      if (constraints.exact) {
        return {
          valid: value === constraints.exact,
          message: `尺寸必须为 ${constraints.exact}`
        }
      }

      if (constraints.min && value < constraints.min) {
        return {
          valid: false,
          message: `尺寸不能小于 ${constraints.min}`
        }
      }

      if (constraints.max && value > constraints.max) {
        return {
          valid: false,
          message: `尺寸不能大于 ${constraints.max}`
        }
      }

      return { valid: true }
    })

    // 位置验证器
    this.validators.set('position', (value, constraints) => {
      if (!constraints?.allowed) return { valid: true }

      return {
        valid: constraints.allowed.includes(value),
        message: `位置必须是: ${constraints.allowed.join(', ')}`
      }
    })

    // 颜色验证器
    this.validators.set('color', (value, constraints) => {
      if (!constraints) return { valid: true }

      // 检查是否为品牌颜色
      if (constraints === 'brand-only') {
        const globalConstraints = this.constraints.get('global')
        return {
          valid: globalConstraints.colors.brandColors.includes(value),
          message: '只能使用品牌颜色'
        }
      }

      // 检查对比度
      if (constraints.contrastRatio) {
        // 这里可以实现对比度计算
        return { valid: true } // 简化实现
      }

      return { valid: true }
    })

    // 内容验证器
    this.validators.set('content', (value, constraints) => {
      if (!constraints) return { valid: true }

      // 长度检查
      if (constraints.maxLength && value.length > constraints.maxLength) {
        return {
          valid: false,
          message: `内容长度不能超过 ${constraints.maxLength} 个字符`
        }
      }

      // 空值检查
      if (constraints.validation === 'no-empty' && (!value || value.trim() === '')) {
        return {
          valid: false,
          message: '内容不能为空'
        }
      }

      // URL验证
      if (constraints.validation === 'valid-url' && value) {
        try {
          new URL(value)
        } catch {
          return {
            valid: false,
            message: '请输入有效的URL'
          }
        }
      }

      return { valid: true }
    })

    // 动画验证器
    this.validators.set('animation', (value, constraints) => {
      if (!constraints) return { valid: true }

      const globalAnim = this.constraints.get('global').animation

      if (value.type && !globalAnim.allowedTypes.includes(value.type)) {
        return {
          valid: false,
          message: `不支持的动画类型: ${value.type}`
        }
      }

      if (value.duration) {
        const durationRange = constraints.duration || globalAnim.durationRange
        if (value.duration < durationRange.min || value.duration > durationRange.max) {
          return {
            valid: false,
            message: `动画时长必须在 ${durationRange.min}-${durationRange.max} 秒之间`
          }
        }
      }

      return { valid: true }
    })
  }

  /**
   * 设置恢复机制
   */
  setupRecoveryMechanisms() {
    this.recovery = {
      // 默认状态恢复
      defaultStates: new Map(),

      // 修改历史
      history: new Map(),

      // 自动修复规则
      autoFix: {
        size: (value, constraints) => {
          if (constraints.min && value < constraints.min) return constraints.min
          if (constraints.max && value > constraints.max) return constraints.max
          return value
        },

        position: (value, constraints) => {
          return constraints.allowed?.includes(value) ? value : constraints.allowed?.[0]
        },

        color: (value, constraints) => {
          if (constraints === 'brand-only') {
            const globalConstraints = this.constraints.get('global')
            return globalConstraints.colors.brandColors[0]
          }
          return value
        }
      }
    }
  }

  /**
   * 验证属性修改
   * @param {string} layerType - 层类型
   * @param {string} property - 属性名
   * @param {any} value - 属性值
   * @param {Object} layerConstraints - 层约束
   * @returns {Object} 验证结果
   */
  validateModification(layerType, property, value, layerConstraints = null) {
    // 获取层级约束
    const typeConstraints = this.constraints.get(layerType)
    if (!typeConstraints) {
      return { valid: true, warnings: ['未知层类型'] }
    }

    // 检查是否允许修改
    if (!typeConstraints.modifiable) {
      return {
        valid: false,
        reason: `${layerType}层不可修改`,
        severity: 'error'
      }
    }

    // 获取属性约束
    const propertyConstraints =
      typeConstraints.properties?.[property] || layerConstraints?.[property]
    if (!propertyConstraints) {
      return { valid: true, warnings: ['无特定约束'] }
    }

    // 使用对应验证器
    const validator = this.validators.get(property)
    if (validator) {
      const result = validator(value, propertyConstraints)
      if (!result.valid) {
        return {
          valid: false,
          reason: result.message,
          severity: 'error',
          suggestedValue: this.getSuggestedValue(property, value, propertyConstraints)
        }
      }
    }

    // 检查冲突
    const conflicts = this.checkConflicts(layerType, property, value)
    if (conflicts.length > 0) {
      return {
        valid: false,
        reason: `修改冲突: ${conflicts.join(', ')}`,
        severity: 'warning'
      }
    }

    return { valid: true }
  }

  /**
   * 检查修改冲突
   * @param {string} layerType - 层类型
   * @param {string} property - 属性名
   * @param {any} value - 属性值
   * @returns {Array} 冲突列表
   */
  checkConflicts(layerType, property, value) {
    const conflicts = []

    // 动画冲突检查
    if (property === 'animation' && layerType === 'adjustable') {
      const globalAnim = this.constraints.get('global').animation
      if (value.concurrentAnimations > globalAnim.maxConcurrentAnimations) {
        conflicts.push(`动画数量超过最大并发数 ${globalAnim.maxConcurrentAnimations}`)
      }
    }

    // 位置冲突检查
    if (property === 'position') {
      // 检查与其他元素的碰撞
      // 这里可以实现更复杂的碰撞检测逻辑
    }

    // 性能冲突检查
    if (property === 'effects' && value.length > 5) {
      conflicts.push('特效过多可能影响性能')
    }

    return conflicts
  }

  /**
   * 获取建议值
   * @param {string} property - 属性名
   * @param {any} currentValue - 当前值
   * @param {Object} constraints - 约束
   * @returns {any} 建议值
   */
  getSuggestedValue(property, currentValue, constraints) {
    const autoFix = this.recovery.autoFix[property]
    if (autoFix) {
      return autoFix(currentValue, constraints)
    }

    // 默认建议值
    if (constraints.default) return constraints.default
    if (constraints.allowed && constraints.allowed.length > 0) return constraints.allowed[0]
    if (constraints.min) return constraints.min
    if (constraints.max) return constraints.max

    return currentValue
  }

  /**
   * 应用自动修复
   * @param {Object} layer - 层对象
   * @param {string} property - 属性名
   * @param {any} invalidValue - 无效值
   * @returns {any} 修复后的值
   */
  applyAutoFix(layer, property, invalidValue) {
    const constraints = this.getPropertyConstraints(layer.type, property)
    return this.getSuggestedValue(property, invalidValue, constraints)
  }

  /**
   * 获取属性约束
   * @param {string} layerType - 层类型
   * @param {string} property - 属性名
   * @returns {Object} 属性约束
   */
  getPropertyConstraints(layerType, property) {
    const typeConstraints = this.constraints.get(layerType)
    return typeConstraints?.properties?.[property] || {}
  }

  /**
   * 保存默认状态
   * @param {string} templateId - 模板ID
   * @param {Object} defaultState - 默认状态
   */
  saveDefaultState(templateId, defaultState) {
    this.recovery.defaultStates.set(templateId, JSON.parse(JSON.stringify(defaultState)))
  }

  /**
   * 恢复到默认状态
   * @param {string} templateId - 模板ID
   * @returns {Object|null} 默认状态
   */
  restoreToDefault(templateId) {
    const defaultState = this.recovery.defaultStates.get(templateId)
    return defaultState ? JSON.parse(JSON.stringify(defaultState)) : null
  }

  /**
   * 记录修改历史
   * @param {string} templateId - 模板ID
   * @param {Object} modification - 修改记录
   */
  recordModification(templateId, modification) {
    if (!this.recovery.history.has(templateId)) {
      this.recovery.history.set(templateId, [])
    }

    const history = this.recovery.history.get(templateId)
    history.push({
      ...modification,
      timestamp: Date.now(),
      validated: true
    })

    // 限制历史记录数量
    if (history.length > 50) {
      history.shift()
    }
  }

  /**
   * 撤销最后修改
   * @param {string} templateId - 模板ID
   * @returns {Object|null} 撤销的修改
   */
  undoModification(templateId) {
    const history = this.recovery.history.get(templateId)
    if (!history || history.length === 0) return null

    return history.pop()
  }

  /**
   * 获取约束摘要
   * @param {string} layerType - 层类型
   * @returns {Object} 约束摘要
   */
  getConstraintsSummary(layerType) {
    const constraints = this.constraints.get(layerType)
    if (!constraints) return {}

    return {
      modifiable: constraints.modifiable,
      removable: constraints.removable,
      allowedProperties: Object.keys(constraints.properties || {}),
      restrictions: this.getRestrictionsSummary(constraints)
    }
  }

  /**
   * 获取限制摘要
   * @param {Object} constraints - 约束对象
   * @returns {Object} 限制摘要
   */
  getRestrictionsSummary(constraints) {
    const summary = {}

    if (constraints.properties) {
      for (const [prop, propConstraints] of Object.entries(constraints.properties)) {
        summary[prop] = {
          hasRestrictions: true,
          type: this.getRestrictionType(propConstraints)
        }
      }
    }

    return summary
  }

  /**
   * 获取限制类型
   * @param {Object} propConstraints - 属性约束
   * @returns {string} 限制类型
   */
  getRestrictionType(propConstraints) {
    if (propConstraints.allowed) return 'enum'
    if (propConstraints.min || propConstraints.max) return 'range'
    if (propConstraints.exact) return 'exact'
    if (propConstraints.validation) return 'validation'
    return 'custom'
  }

  /**
   * 清理资源
   */
  cleanup() {
    this.constraints.clear()
    this.validators.clear()
    this.recovery.defaultStates.clear()
    this.recovery.history.clear()
    this.initialized = false
  }
}

export default new TemplateConstraints()
